export const comunasMvp = [
  "Santiago",
  "Providencia",
  "Las Condes",
  "Ñuñoa",
  "Macul",
  "La Florida",
  "Maipú",
  "Puente Alto",
  "San Miguel",
  "Estación Central",
  "Independencia",
  "Recoleta",
  "Vitacura",
  "Lo Barnechea",
  "Huechuraba",
  "Quilicura",
  "Peñalolén",
  "La Reina",
  "San Joaquín",
  "Cerrillos",
  "Pudahuel",
  "La Cisterna",
  "El Bosque",
  "San Bernardo",
  "Colina",
  "Lampa",
  "Padre Hurtado",
  "Peñaflor",
  "Talagante",
  "Buin",
  "Calera de Tango",
  "Paine",
  "Pirque",
  "San José de Maipo",
  "Melipilla",
  "Cerro Navia",
  "Conchalí",
  "La Granja",
  "La Pintana",
  "Lo Espejo",
  "Lo Prado",
  "Pedro Aguirre Cerda",
  "Quinta Normal",
  "Renca",
  "San Ramón",
].sort((a, b) => a.localeCompare(b, "es"));
